###########
# site.title

title: "Couch Potato"
subtitle: "A command based senario description project"

#########################
# more settings

markdown: kramdown

exclude:
  - README.md
  - LICENSE.md
